### PR TITLE
How to investigate "failing smoke tests"

### PR DESCRIPTION
**Pull request by kptdobe**
PR for https://github.com/adobe/helix-cli/issues/920

### CODE REVIEW

**Comment by tripodsan** [comment]
good so far. but ti doesn't explain, how I can run the smoke test locally in order to debug what failed.

It would be good to either have a script that does the same as the CI, or at least describe the steps, as in https://github.com/adobe/helix-cli/issues/920#issuecomment-496049662

**Comment by kptdobe** [comment]
Ok, I can add this. I never used that procedure so far ;)

**Comment by tripodsan** [comment]
> Ok, I can add this. I never used that procedure so far ;)

how did you debug failing tests then?

**Comment by kptdobe** [comment]
When I develop, I usually already have a patched cli (using `npm link` or `npm pack + add`) with my PR code in there. Since the smoke tests are pretty basic, using `hlx up` on any project usually is enough to see the error that my code introduced.

But I agree that having a documented way / automated way to get the full environment like in the tests is useful.

**Pull request merged**
